version: "3"
services:
  juniper:
    container_name: juniper
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      - WEB_PORT=3000
    ports:
      - "3000:3000"
    volumes:
      